- name: Install notify-send dependency
  become: true
  apt:
    name: libnotify-bin
    state: present
    update_cache: yes

- name: Ensure ~/bin is in PATH in .bashrc
  become: true
  become_user: zemfyre
  lineinfile:
    path: /home/zemfyre/.bashrc
    insertafter: EOF
    line: 'export PATH="$HOME/bin:$PATH"'
    create: yes
    state: present

- name: Ensure dunst is installed
  become: true
  apt:
    name: dunst
    state: present
    update_cache: true

- name: Enable lingering for user so user services run without active login session
  become: true
  command: loginctl enable-linger zemfyre

