services:
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        ports:
          - "${MOSQUITTO_PORT_EXT:-51883}:1883"
          - "${MOSQUITTO_WS_PORT_EXT:-59001}:9001"
        volumes:
          - ./mosquitto/config:/mosquitto/config/
        networks:
          - zemfyre
    nodered:
        build:
            context: ./nodered
            dockerfile: Dockerfile
        restart: always
        ports:
            - "${NODERED_PORT_EXT:-51880}:1880"
        volumes:
            - ./nodered/data:/data
            - ./nodered/nodes:/data/nodes
            - /data/node_modules
        networks:
          - zemfyre

    influx:
        container_name: influxdb
        image: influxdb:alpine
        restart: unless-stopped
        environment:
            - INFLUXDB_INIT_ORG=Zemfyre
            - INFLUXDB_INIT_BUCKET=ZUS80LP
            - INFLUXDB_LOG_LEVEL=debug
        ports:
            - "${INFLUXDB_PORT_EXT:-58086}:8086"
        volumes:
            - ./influx/data:/var/lib/influxdb2
            - ./influx/config:/etc/influxdb2
        networks:
          - zemfyre

    grafana:
        depends_on:
            - influx
        container_name: grafana
        restart: always
        build:
          context: ./grafana
          dockerfile: Dockerfile
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
            - GF_INSTALL_PLUGINS=natel-plotly-panel

        volumes:
            - ./grafana/data/grafana.db:/var/lib/grafana/grafana.db
            - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/provisioning:/etc/grafana/provisioning
        ports:
            - "${GRAFANA_PORT_EXT:-53000}:3000"
        networks:
          - zemfyre

networks:
  zemfyre:
    driver: bridge




