services:
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        ports:
          - "${MOSQUITTO_PORT_EXT}:1883"
          - "${MOSQUITTO_WS_PORT_EXT}:9001"
        volumes:
          - ./mosquitto/config:/mosquitto/config/
        networks:
          - zemfyre
    nodered:
        build:
            context: ./nodered
            dockerfile: Dockerfile
        restart: always
        ports:
            - "${NODERED_PORT_EXT:-51880}:1880"
        volumes:
            - ./nodered/data:/data
            - ./nodered/nodes:/data/nodes
            - /data/node_modules
        networks:
          - zemfyre

    influx:
        container_name: influxdb
        image: influxdb:alpine
        restart: unless-stopped
        environment:
            - INFLUXDB_INIT_ORG=Zemfyre
            - INFLUXDB_INIT_BUCKET=ZUS80LP
            - INFLUXDB_LOG_LEVEL=debug
        ports:
            - "${INFLUXDB_PORT_EXT:-58086}:8086"
        volumes:
            - ./influx/data:/var/lib/influxdb2
            - ./influx/config:/etc/influxdb2
        networks:
          - zemfyre

    grafana:
        depends_on:
            - influx
        container_name: grafana
        restart: always
        build:
          context: ./grafana
          dockerfile: Dockerfile
        user: "grafana"
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - GF_AUTH_ANONYMOUS_ENABLED=${GRAFANA_AUTH_ANONYMOUS_ENABLED}
            - GF_AUTH_ANONYMOUS_ORG_ROLE=${GRAFANA_AUTH_ANONYMOUS_ORG_ROLE}
            - GF_AUTH_DISABLE_LOGIN_FORM=${GRAFANA_AUTH_DISABLE_LOGIN_FORM}

        volumes:
            # - ${GRAFANA_VOLUME:-grafana-storage}:/var/lib/grafana
            - ./grafana/data:/var/lib/grafana
            - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/provisioning:/etc/grafana/provisioning
        ports:
            - "${GRAFANA_PORT_EXT:-53000}:3000"
        networks:
          - zemfyre
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer_data:/data
        networks:
            - zemfyre
    admin:
        build:
            context: ./admin
            dockerfile: Dockerfile
        container_name: admin
        restart: always
        ports:
            - "${ADMIN_PORT:-51850}:80"
        networks:
            - zemfyre
networks:
  zemfyre:
    driver: bridge




