# docker-compose.pi.yml
version: "3.8"

services:
  mosquitto:
    networks:
      - default

  nodered:
    networks:
      - default

  influx:
    networks:
      - default

  grafana:
    networks:
      - default

  portainer:
    networks:
      - default

  admin:
    networks:
      - default

  api:
    networks:
      - default

networks:
  default:
    driver: bridge
