version: '3.8'

services:
  sensor-simulator:
    build:
      context: ./sensor-simulator
      dockerfile: Dockerfile
    container_name: sensor-simulator
    restart: unless-stopped
    volumes:
      # Bind mount to local filesystem (accessible by local agent on Windows)
      - ./sensor-simulator/sockets:/tmp/sensors
    environment:
      # Simulator Configuration
      - NUM_SENSORS=${SIM_NUM_SENSORS:-3}
      - SOCKET_DIR=/tmp/sensors
      - PUBLISH_INTERVAL_MS=${SIM_PUBLISH_INTERVAL_MS:-60000}
      - ENABLE_FAILURES=${SIM_ENABLE_FAILURES:-true}
      - FAILURE_CHANCE=${SIM_FAILURE_CHANCE:-0.05}
      - RECONNECT_DELAY_MS=${SIM_RECONNECT_DELAY_MS:-10000}
      - DATA_FORMAT=${SIM_DATA_FORMAT:-json}
      - EOM_DELIMITER=${SIM_EOM_DELIMITER:-\n}
      - LOG_LEVEL=${SIM_LOG_LEVEL:-info}
    networks:
      - Iotistic-net

networks:
  Iotistic-net:
    driver: bridge
