apiVersion: v1
kind: ConfigMap
metadata:
  name: cb4c867f4-customer-instance-prometheus-config
  namespace: customer-b4c867f4
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
      external_labels:
        customer_id: "cust-b4c867f44a92453aba8a2fe3fe5d6e5e"
        customer_plan: "starter"
        cluster: "cust-b4c867f44a92453aba8a2fe3fe5d6e5e"

    scrape_configs:
    # API metrics
    - job_name: 'api'
      static_configs:
      - targets: ['cb4c867f4-customer-instance-api:3002']
        labels:
          service: 'api'
          customer_id: "cust-b4c867f44a92453aba8a2fe3fe5d6e5e"
    # MQTT exporter metrics
    - job_name: 'mqtt-exporter'
      static_configs:
      - targets: ['mqtt-exporter:9234']
        labels:
          service: 'mqtt-exporter'
          customer_id: "cust-b4c867f44a92453aba8a2fe3fe5d6e5e"
    # PostgreSQL metrics
    - job_name: 'postgres'
      static_configs:
      - targets: ['cb4c867f4-customer-instance-postgres:9187']
        labels:
          service: 'postgres'
          customer_id: "cust-b4c867f44a92453aba8a2fe3fe5d6e5e"
