{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opencost
  namespace: {{ .Values.serviceMonitor.namespace | default "monitoring" }}
  labels:
    app: opencost
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: {{ .Release.Name }}
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: opencost
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
