apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencost
  namespace: {{ .Values.serviceMonitor.namespace | default "monitoring" }}
  labels:
    app: opencost
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opencost
  labels:
    app: opencost
    app.kubernetes.io/name: opencost
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - services
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opencost
  labels:
    app: opencost
    app.kubernetes.io/name: opencost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencost
subjects:
- kind: ServiceAccount
  name: opencost
  namespace: {{ .Values.serviceMonitor.namespace | default "monitoring" }}
