---
- name: Install kiosk packages
  apt:
    name: "{{ kiosk_packages }}"
    state: present
    update_cache: true
  become: true

- name: Create kiosk user home directory
  file:
    path: "/home/{{ kiosk_user }}"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'
  become: true

- name: Create .xinitrc for kiosk mode
  template:
    src: xinitrc.j2
    dest: "/home/{{ kiosk_user }}/.xinitrc"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'
  become: true

- name: Create getty override directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Enable automatic login for kiosk user
  lineinfile:
    path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    line: "ExecStart=-/sbin/agetty --autologin {{ kiosk_user }} --noclear %I $TERM"
    regexp: "^ExecStart="
    create: true
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: reload systemd

- name: Configure automatic X11 startup in .bashrc
  lineinfile:
    path: "/home/{{ kiosk_user }}/.bashrc"
    line: "[ -z \"$DISPLAY\" ] && [ \"$(tty)\" = \"/dev/tty1\" ] && startx"
    create: true
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0644'
  become: true
