---
# Config tasks

# - name: Ensure git is installed
#   apt:
#     name: git
#     state: present
#   become: true

# - name: Ensure curl is installed
#   apt:
#     name: curl
#     state: present
#   become: true

# - name: Check if ngrok is running as a systemd service
#   shell: systemctl is-active ngrok.service
#   register: ngrok_status
#   changed_when: false
#   failed_when: false

# - name: Print ngrok service status
#   debug:
#     msg: "ngrok is {{ 'running' if ngrok_status.stdout == 'active' else 'not running or not installed' }}"


# - name: Ensure repo directory exists
#   file:
#     path: "{{ repo_dir }}"
#     state: directory
#     owner: "{{ kiosk_user }}"
#     group: "{{ kiosk_user }}"
#     mode: '0755'
#   become: true

# - name: Download or update zemfyre-sensor repo
#   git:
#     repo: "{{ repo_url }}"
#     dest: "{{ repo_dir }}"
#     update: yes
#     force: yes

# - name: Copy Raspberry Pi-specific .env file to repo directory
#   copy:
#     src: "{{ playbook_dir }}/.env.pi"
#     dest: "{{ repo_dir }}/.env"
#     mode: '0644'

- name: Fix Grafana data directory ownership (allow Grafana container access)
  file:
    path: "{{ repo_dir }}/grafana/data"
    owner: 472
    group: "{{ ansible_user_gid }}"
    recurse: yes
    state: directory
  become: true

- name: Set directories to 775 and files to 664 in Grafana data
  shell: |
    find {{ repo_dir }}/grafana/data -type d -exec chmod 775 {} \;
    find {{ repo_dir }}/grafana/data -type f -exec chmod 664 {} \;
  become: true



# - name: Debug final kiosk setup
#   debug:
#     msg: "Kiosk setup complete. Mode detected: {{ hostvars[inventory_hostname]['desktop_mode'] | default('unknown') }}"

# - name: Reboot Raspberry Pi to apply changes and start kiosk mode
#   reboot:
#     msg: "Reboot initiated by Ansible to start kiosk mode with zemfyre-sensor dashboard."
#     connect_timeout: 5
#     reboot_timeout: 120
#     pre_reboot_delay: 5