# Common values shared across all customer instances
# Customer-specific overrides go in individual customer files

# Resource defaults
resources:
  api:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  dashboard:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  postgres:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  mosquitto:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Storage defaults
persistence:
  postgres:
    size: 10Gi
    storageClass: standard
  
  mosquitto:
    size: 1Gi
    storageClass: standard

# Monitoring defaults (Starter/Professional - shared Prometheus)
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
  
# Security defaults
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Networking defaults
service:
  type: ClusterIP

# Ingress defaults
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true
