apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: ddwqd51wttou8f
    access: proxy
    url: http://influx:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: Zemfyre
      defaultBucket: ZUS80LP
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_TOKEN
