/**
 * Migration: Add MQTT credentials to device table
 * 
 * Adds columns to store MQTT connection credentials provided by
 * the cloud API during device provisioning:
 * - mqttUsername: MQTT client username (usually device UUID)
 * - mqttPassword: MQTT client password (generated by API)
 * - mqttBrokerUrl: MQTT broker connection URL
 */

exports.up = function(knex) {
  return knex.schema.table('device', function(table) {
    table.string('mqttUsername', 255).nullable();
    table.string('mqttPassword', 255).nullable();
    table.string('mqttBrokerUrl', 255).nullable();
  });
};

exports.down = function(knex) {
  return knex.schema.table('device', function(table) {
    table.dropColumn('mqttUsername');
    table.dropColumn('mqttPassword');
    table.dropColumn('mqttBrokerUrl');
  });
};
