# Billing - Docker Compose for Local Development

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing123
      POSTGRES_DB: billing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Auto-run migrations
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billing"]
      interval: 5s
      timeout: 5s
      retries: 5

  billing:
    build: .
    ports:
      - "3100:3100"
    environment:
      NODE_ENV: development
      PORT: 3100
      DATABASE_URL: postgres://billing:billing123@postgres:5432/billing
      
      # Stripe (use your test keys)
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      # Get this from: docker logs billing-stripe-cli (look for "Ready! Your webhook signing secret is whsec_...")
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      
      # Stripe Price IDs (create these in Stripe dashboard)
      STRIPE_PRICE_STARTER: ${STRIPE_PRICE_STARTER}
      STRIPE_PRICE_PROFESSIONAL: ${STRIPE_PRICE_PROFESSIONAL}
      STRIPE_PRICE_ENTERPRISE: ${STRIPE_PRICE_ENTERPRISE}
      
      # License keys
      LICENSE_PRIVATE_KEY_PATH: ${LICENSE_PRIVATE_KEY_PATH}
      LICENSE_PUBLIC_KEY_PATH: ${LICENSE_PUBLIC_KEY_PATH}

      # Trial configuration
      DEFAULT_TRIAL_DAYS: 14
    volumes:
      - ./keys:/app/keys
      - ./dist:/app/dist
    depends_on:
      postgres:
        condition: service_healthy

  # Stripe CLI for webhook testing
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: billing-stripe-cli
    command: listen --forward-to http://billing:3100/api/webhooks/stripe --skip-verify
    environment:
      # Set your Stripe API key
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - billing
    # Note: On first run, you'll need to get the webhook signing secret
    # Run: docker logs billing-stripe-cli
    # Look for: "Ready! Your webhook signing secret is whsec_..." 
    # Update STRIPE_WEBHOOK_SECRET in billing service with this value

volumes:
  postgres_data:
