{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-instance.fullname" . }}-exporter
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "customer-instance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: exporter
  template:
    metadata:
      labels:
        {{- include "customer-instance.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: exporter
    spec:
      containers:
      - name: exporter
        image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
        ports:
        - name: metrics
          containerPort: {{ .Values.exporter.port }}
        env:
        - name: CUSTOMER_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "customer-instance.fullname" . }}-secrets
              key: CUSTOMER_ID
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "customer-instance.fullname" . }}-secrets
              key: DATABASE_URL
        resources:
          {{- toYaml .Values.exporter.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer-instance.fullname" . }}-exporter
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.exporter.port }}
    targetPort: metrics
  selector:
    {{- include "customer-instance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
{{- end }}
