{{- if and .Values.mosquitto.enabled .Values.mosquitto.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-instance.fullname" . }}-mosquitto-exporter
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "customer-instance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mqtt-exporter
  template:
    metadata:
      labels:
        {{- include "customer-instance.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mqtt-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9234"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: mosquitto-exporter
        image: "{{ .Values.mosquitto.metrics.exporter.image.repository }}:{{ .Values.mosquitto.metrics.exporter.image.tag }}"
        args:
        - --endpoint=tcp://{{ include "customer-instance.fullname" . }}-mosquitto:{{ .Values.mosquitto.ports.mqtt }}
        ports:
        - name: metrics
          containerPort: 9234
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.mosquitto.metrics.exporter.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer-instance.fullname" . }}-mosquitto-exporter
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9234
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "customer-instance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt-exporter
{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "customer-instance.fullname" . }}-mosquitto-exporter
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt-exporter
spec:
  selector:
    matchLabels:
      {{- include "customer-instance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mqtt-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
{{- end }}
{{- end }}
