{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "customer-instance.fullname" . }}
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "customer-instance.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
    - protocol: TCP
      port: {{ .Values.dashboard.port }}
    - protocol: TCP
      port: {{ .Values.exporter.port }}
  # Allow internal pod communication
  - from:
    - podSelector:
        matchLabels:
          {{- include "customer-instance.selectorLabels" . | nindent 10 }}
  egress:
  # Allow DNS
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  # Allow internal pod communication
  - to:
    - podSelector:
        matchLabels:
          {{- include "customer-instance.selectorLabels" . | nindent 10 }}
  # Allow external HTTPS (for API calls, updates)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
  # Allow external HTTP (for package downloads)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
{{- end }}
