{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "customer-instance.fullname" . }}
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.cpu }}
    requests.memory: {{ .Values.resourceQuota.memory }}
    limits.cpu: {{ .Values.resourceQuota.cpu }}
    limits.memory: {{ .Values.resourceQuota.memory }}
    persistentvolumeclaims: {{ .Values.resourceQuota.pvcs | quote }}
    services: {{ .Values.resourceQuota.services | quote }}
{{- end }}
