{{- if .Values.monitoring.enabled }}
{{- if not .Values.monitoring.dedicated }}
---
# ServiceMonitor for shared Prometheus
# Shared Prometheus in 'monitoring' namespace will scrape these metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "customer-instance.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-instance.labels" . | nindent 4 }}
    prometheus: kube-prometheus  # Selector for shared Prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  # API metrics endpoint
  - port: http
    path: /metrics
    interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
    relabelings:
    # Add customer identification labels
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: customer_namespace
    - sourceLabels: []
      targetLabel: customer_id
      replacement: {{ .Values.customer.id | quote }}
    - sourceLabels: []
      targetLabel: customer_plan
      replacement: {{ .Values.customer.plan | default "starter" | quote }}
    - sourceLabels: []
      targetLabel: customer_company
      replacement: {{ .Values.customer.companyName | quote }}
  
  {{- if .Values.mosquitto.metrics.enabled }}
  # Mosquitto MQTT broker metrics
  - port: mqtt-metrics
    path: /metrics
    interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
    relabelings:
    - sourceLabels: []
      targetLabel: customer_id
      replacement: {{ .Values.customer.id | quote }}
    - sourceLabels: []
      targetLabel: service
      replacement: mosquitto
  {{- end }}
  
  {{- if .Values.postgres.metrics.enabled }}
  # PostgreSQL database metrics
  - port: postgres-metrics
    path: /metrics
    interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
    relabelings:
    - sourceLabels: []
      targetLabel: customer_id
      replacement: {{ .Values.customer.id | quote }}
    - sourceLabels: []
      targetLabel: service
      replacement: postgres
  {{- end }}
{{- end }}
{{- end }}
