- name: Install RealVNC VNC Server
  apt:
    name: realvnc-vnc-server
    state: present
    update_cache: yes

- name: Enable VNC server service
  systemd:
    name: vncserver-x11-serviced.service
    enabled: yes
    state: started