- name: Ensure [Time] section exists in timesyncd.conf
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^\[Time\]'
    line: '[Time]'
    create: yes
    state: present

- name: Configure systemd-timesyncd NTP server
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^NTP='
    line: 'NTP={{ ntp_server_ip }}'
    insertafter: '^\[Time\]'
    create: yes

- name: Set fallback NTP servers to Debian pool
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^FallbackNTP='
    line: 'FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org'
    insertafter: '^\[Time\]'
    create: yes

- name: Allow systemd-timesyncd to handle large offsets (48 hours)
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^RootDistanceMaxSec='
    line: 'RootDistanceMaxSec=172800'
    insertafter: '^\[Time\]'
    create: yes

- name: Enable and start systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes
    state: restarted
  ignore_errors: true

# ---------------- Docker Installation ----------------

# Pre-flight: Clean up any malformed Docker repository files
- name: Remove potentially malformed docker.list (pre-flight)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  ignore_errors: true

# Get Debian/Ubuntu codename
- name: Get system codename
  ansible.builtin.command: lsb_release -cs
  register: debian_name
  changed_when: false

# Normalize codename to Docker-supported ones
- name: Map unsupported codenames to supported Docker repos
  ansible.builtin.set_fact:
    docker_codename: >-
      {% if debian_name.stdout in ['noble', 'trixie', 'testing', 'sid'] %}
        bookworm
      {% elif debian_name.stdout == 'jammy' %}
        bullseye
      {% else %}
        {{ debian_name.stdout }}
      {% endif %}

# Debug output for safety
- debug:
    msg: "Using Docker codename '{{ docker_codename }}' for '{{ debian_name.stdout }}'"

# Add Docker’s GPG key
- name: Add Docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

# Determine architecture
- name: Determine architecture for Docker packages
  ansible.builtin.set_fact:
    architecture: >-
      {% if ansible_architecture == 'x86_64' %}
        amd64
      {% elif ansible_architecture in ['aarch64', 'arm64'] %}
        arm64
      {% elif ansible_architecture in ['armv7l', 'armv6l'] %}
        armhf
      {% else %}
        amd64
      {% endif %}

- name: Ensure apt sources directory exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Check if Docker is already installed
  ansible.builtin.command: docker --version
  register: docker_version
  ignore_errors: true
  changed_when: false

- name: Display current Docker version if installed
  ansible.builtin.debug:
    msg: "Docker already installed: {{ docker_version.stdout }}"
  when: docker_version.rc == 0

- name: Install Docker using official convenience script
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    rm /tmp/get-docker.sh
  when: docker_version.rc != 0
  register: docker_install
  changed_when: true

- name: Display Docker installation output
  ansible.builtin.debug:
    msg: "{{ docker_install.stdout_lines }}"
  when: docker_version.rc != 0 and docker_install.stdout_lines is defined

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_verify
  changed_when: false

- name: Display Docker version after installation
  ansible.builtin.debug:
    msg: "✅ Docker installed: {{ docker_verify.stdout }}"

- name: Ensure Docker service is enabled and started
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true


- name: Perform system upgrade
  ansible.builtin.apt:
    upgrade: dist
  tags:
    - system-upgrade

- name: Clean up unused packages
  ansible.builtin.apt:
    autoremove: true
  tags:
    - system-upgrade

- name: Remove deprecated pip dependencies (>= Debian 12)
  ansible.builtin.pip:
    name: supervisor
    executable: "{{ lookup('env', 'HOME') }}/installer_venv/bin/pip"
    state: absent
  when:
    - ansible_distribution_major_version | int >= 12
    - lookup('env', 'HOME') is defined
    - (lookup('env', 'HOME') + '/installer_venv/bin/pip') is file


- name: Remove deprecated pip dependencies (>= Debian 12)
  ansible.builtin.pip:
    name: supervisor
    executable: /home/{{ lookup('env', 'USER') }}/installer_venv/bin/pip
    state: absent
  when:
    - ansible_distribution_major_version | int >= 12