---
# roles/network/tasks/main.yml

- name: Detect the NetworkManager connection name for eth0
  command: nmcli -t -f NAME,DEVICE connection show
  register: nmcli_conn_list
  changed_when: false
  become: true

- name: Set variable for connection name of eth0
  set_fact:
    nm_connection: "{{ item.split(':')[0] }}"
  loop: "{{ nmcli_conn_list.stdout_lines }}"
  when: item.split(':')[1] == nm_interface
  vars:
    nm_interface: "eth0"

- name: Configure wired network connection (only if not present)
  block:
    - name: Set static IP address
      command: nmcli connection modify "{{ nm_connection }}" ipv4.addresses "{{ nm_ip }}"
      become: true

    - name: Set manual method for IPv4
      command: nmcli connection modify "{{ nm_connection }}" ipv4.method manual
      become: true

    - name: Set gateway
      command: nmcli connection modify "{{ nm_connection }}" ipv4.gateway "{{ nm_gateway }}"
      become: true

    - name: Set DNS
      command: nmcli connection modify "{{ nm_connection }}" ipv4.dns "{{ nm_dns }}"
      become: true

    - name: Bring connection down
      command: nmcli connection down "{{ nm_connection }}" || true
      ignore_errors: true
      become: true

    - name: Bring connection up again
      command: nmcli connection up "{{ nm_connection }}"
      become: true
  when: nm_connection is defined

  vars:
    nm_ip: "192.168.1.30/24"
    nm_gateway: ""
    nm_dns: ""
