apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iotistic-customers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # This is the "App of Apps" pattern
  # Points to the directory containing all customer Application manifests
  source:
    repoURL: https://github.com/dsamborschi/zemfyre-sensor
    targetRevision: HEAD
    path: argocd/customers
    directory:
      recurse: true
      jsonnet: {}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true      # Remove resources that are no longer in git
      selfHeal: true   # Auto-sync when cluster state drifts from git
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iotistic-customers
  namespace: argocd
spec:
  description: Iotistic customer instances
  
  # Allow deploying to any namespace
  destinations:
    - namespace: 'customer-*'
      server: https://kubernetes.default.svc
  
  # Allow resources from this repo only
  sourceRepos:
    - https://github.com/dsamborschi/zemfyre-sensor
  
  # Allow all resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
