---
- name: Deploy zemfyre-sensor to Raspberry Pi (Headless and Desktop)
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/dsamborschi/zemfyre-sensor.git"
    repo_dir: "iotistic"
    kiosk_user: "zemfyre"
    ntp_server_ip: "192.168.1.100"
    nm_ip: "192.168.1.30/24"
    nm_gateway: ""
    nm_dns: ""
    
  pre_tasks:
    - name: Load environment variables from .env file
      set_fact:
        grafana_port_ext: "{{ lookup('file', playbook_dir + '/.env.pi').splitlines() | select('match', '^GRAFANA_PORT_EXT=') | map('regex_replace', '^GRAFANA_PORT_EXT=(.*)$', '\\1') | list | first | default('3000') }}"
        admin_port: "{{ lookup('file', playbook_dir + '/.env.pi').splitlines() | select('match', '^ADMIN_PORT=') | map('regex_replace', '^ADMIN_PORT=(.*)$', '\\1') | list | first | default('51850') }}"

  roles:
    - system
    - network
    - kiosk
    - config



   
