---
- name: Deploy zemfyre-sensor to Raspberry Pi (Headless and Desktop)
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/dsamborschi/zemfyre-sensor.git"
    repo_dir: "iotistic"
    kiosk_user: "zemfyre"
    ntp_server_ip: "192.168.2.121"
    nm_ip: "192.168.2.30/24"
    nm_gateway: ""
    nm_dns: ""
    
  pre_tasks:
    - name: Load environment variables from environment
      set_fact:
        grafana_port_ext: "{{ lookup('env', 'GRAFANA_PORT_EXT') | default('53000') }}"
        admin_port: "{{ lookup('env', 'ADMIN_PORT_EXT') | default('51850') }}"

  roles:
    - system
    - network
    - kiosk



   
