---
- name: Deploy zemfyre-sensor to Raspberry Pi (Headless and Desktop)
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/dsamborschi/zemfyre-sensor.git"
    repo_dir: "iotistic"
    kiosk_user: "zemfyre"
    ntp_server_ip: "192.168.2.121"
    nm_ip: "192.168.2.30/24"
    nm_gateway: ""
    nm_dns: ""
  roles:
    - system
    - network



   
