---
- name: Deploy zemfyre-sensor to Raspberry Pi
  hosts: raspberrypi
  become: yes
  vars:
    repo_url: "https://github.com/dsamborschi/zemfyre-sensor.git"
    repo_dir: "zemfyre-sensor"
    setup_script: "setup.sh"
    kiosk_url: "http://localhost:53000/d/ddwxbtmmr6nlsa/zus80lp?orgId=1&refresh=5s&from=now-5m&to=now&kiosk"
    autostart_file: "/etc/xdg/lxsession/LXDE-pi/autostart"

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
      become: yes

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
      become: yes

    - name: Ensure Chromium and kiosk tools are installed
      apt:
        name:
          - chromium-browser
          - unclutter
          - xdotool
        state: present
        update_cache: yes

    - name: Check if autostart file exists
      stat:
        path: "{{ autostart_file }}"
      register: autostart_file_stat
    
    - name: Read current kiosk autostart content (if exists)
      slurp:
        path: "{{ autostart_file }}"
      register: autostart_file_content
      when: autostart_file_stat.stat.exists

    - name: Suppress Chromium crash recovery popup
      blockinfile:
        path: "{{ autostart_file }}"
        block: |
          @bash -c 'sed -i "s/\\"exited_cleanly\\": false/\\"exited_cleanly\\": true/" /home/pi/.config/chromium/Default/Preferences && \
                    sed -i "s/\\"exit_type\\": \\"Crashed\\"/\\"exit_type\\": \\"Normal\\"/" /home/pi/.config/chromium/Default/Preferences'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Suppress Chromium crash recovery"


    - name: Create kiosk autostart file only if kiosk_url is not set
      blockinfile:
        path: "{{ autostart_file }}"
        block: |
          @lxpanel --profile LXDE-pi
          @pcmanfm --desktop --profile LXDE-pi
          @xscreensaver -no-splash

          @xset s off
          @xset -dpms
          @xset s noblank
          @unclutter -idle 0.1 -root
          @bash -c 'sed -i "s/\\"exited_cleanly\\": false/\\"exited_cleanly\\": true/" /home/pi/.config/chromium/Default/Preferences && \
                    sed -i "s/\\"exit_type\\": \\"Crashed\\"/\\"exit_type\\": \\"Normal\\"/" /home/pi/.config/chromium/Default/Preferences && \
                    chromium-browser --noerrdialogs --disable-infobars --disable-session-crashed-bubble --no-first-run --disable-features=TranslateUI --disable-component-update --disable-pinch --overscroll-history-navigation=0 --kiosk {{ kiosk_url }}'
        create: yes
        owner: root
        group: root
        mode: '0644'


    - name: Download or update zemfyre-sensor repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        update: yes
        force: yes

    - name: Ensure setup.sh is executable
      file:
        path: "{{ repo_dir }}/{{ setup_script }}"
        mode: '0755'

    - name: Run setup.sh
      command: ./{{ setup_script }}
      args:
        chdir: "{{ repo_dir }}"
      become: yes
      register: setup_output
      environment:
        MOSQUITTO_PORT_EXT: "{{ lookup('env', 'MOSQUITTO_PORT_EXT') | default('1883') }}"
        MOSQUITTO_WS_PORT_EXT: "{{ lookup('env', 'MOSQUITTO_WS_PORT_EXT') | default('59001') }}"
        NODERED_PORT_EXT: "{{ lookup('env', 'NODERED_PORT_EXT') | default('51880') }}"
        INFLUXDB_PORT_EXT: "{{ lookup('env', 'INFLUXDB_PORT_EXT') | default('58086') }}"
        GRAFANA_PORT_EXT: "{{ lookup('env', 'GRAFANA_PORT_EXT') | default('53000') }}"
    
    - name: Print setup.sh stdout
      debug:
       msg: "{{ setup_output.stdout_lines }}"
      when: setup_output is defined

    - name: Reboot Raspberry Pi to apply kiosk mode
      reboot:
        msg: "Reboot initiated by Ansible to start kiosk mode with updated Chromium settings."
        connect_timeout: 5
        reboot_timeout: 120
        pre_reboot_delay: 5
        post_reboot_delay: 10
