name: Ansible Lint

on:
  push:
    branches:
      - master
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - master
    paths:
      - 'ansible/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.9.0    # pick a version / release
        with:
          args: ""
          working_directory: "ansible/"
