name: Build and Push Api Image

on: 
  push:
    branches:
      - master
    paths:
      - 'api/**' 

jobs:
  buildx:
    name: Build & Push Api Image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - board: pi3
            platform: linux/arm/v7
          - board: pi4
            platform: linux/arm/v7
          - board: pi4-64
            platform: linux/arm64/v8
          - board: pi5
            platform: linux/arm64/v8
          - board: x86
            platform: linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache/${{ matrix.board }}
          key: buildx-api-${{ matrix.board }}-${{ github.sha }}
          restore-keys: |
            buildx-grafana-${{ matrix.board }}-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Admin image
        uses: docker/build-push-action@v5
        with:
          context: ./admin
          file: ./admin/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.board }}
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ matrix.board }},mode=max
          tags: |
            iotistic/zemfyre-api:latest-${{ matrix.board }}
