name: Build and Push Billing Exporter Image

on: 
  push:
    branches:
      - master
    paths:
      - 'billing-exporter/**' 
      - '.github/workflows/build-exporter.yml'

jobs:
  buildx:
    name: Build & Push Billing Exporter Image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - board: x86
            platform: linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache/${{ matrix.board }}
          key: buildx-exporter-${{ matrix.board }}-${{ github.sha }}
          restore-keys: |
            buildx-exporter-${{ matrix.board }}-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Billing Exporter image
        uses: docker/build-push-action@v5
        with:
          context: ./billing-exporter
          file: ./billing-exporter/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.board }}
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ matrix.board }},mode=max
          tags: |
            iotistic/exporter:latest
