name: Build, Test & Push Device Agent

on: 
  push:
    branches:
      - master
    paths:
      - 'agent/**' 

jobs:
  buildx:
    name: Build, Test & Push Device Agent
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - board: pi4
            platform: linux/arm/v7
          - board: pi4-64
            platform: linux/arm64/v8
          # - board: pi5
          #   platform: linux/arm64/v8
          - board: x86
            platform: linux/amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache/${{ matrix.board }}
          key: buildx-agent-v2-${{ matrix.board }}-${{ github.sha }}
          restore-keys: |
            buildx-agent-v2-${{ matrix.board }}-

      # Build locally but DO NOT push yet
      - name: Build image (local only)
        uses: docker/build-push-action@v5
        with:
          context: ./agent
          file: ./agent/Dockerfile
          load: true
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.board }}
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ matrix.board }},mode=max
          tags: |
            iotistic/agent:test-${{ matrix.board }}

      - name: Run api tests
        run: |
          docker run --rm \
            --platform ${{ matrix.platform }} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/agent/test:/app/test \
            -e CLOUD_API_ENDPOINT="http://localhost:3002" \
            -e API_URL="http://localhost:48484" \
            -e USE_REAL_DOCKER="false" \
            iotistic/agent:test-${{ matrix.board }} \
            bash /app/test/run-ci-tests.sh


      # Login to Docker Hub (only if tests passed)
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build again but this time PUSH to registry
      - name: Build & Push final image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./agent
          file: ./agent/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.board }}
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ matrix.board }},mode=max
          tags: |
            iotistic/agent:latest-${{ matrix.board }}
