name: Sync install.sh to Azure Blob

on:
  # Run after test-full-installation workflow completes successfully
  workflow_run:
    workflows: ["Test Full Installation"]
    types:
      - completed
    branches:
      - master
  
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  upload-server-bat:
    runs-on: ubuntu-latest
    # Only run if the test workflow succeeded (or if manually triggered)
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload install.sh
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name scripts \
            --name install.sh \
            --file bin/install.sh \
            --overwrite true \
            --content-type application/octet-stream \
            --content-disposition "attachment; filename=install.sh"
