---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-exporter
  namespace: customer-abc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: billing-exporter-role
  namespace: customer-abc
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: billing-exporter-binding
  namespace: customer-abc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: billing-exporter-role
subjects:
- kind: ServiceAccount
  name: billing-exporter
  namespace: customer-abc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-exporter
  namespace: customer-abc
  labels:
    app: billing-exporter
    component: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-exporter
  template:
    metadata:
      labels:
        app: billing-exporter
        component: billing
    spec:
      serviceAccountName: billing-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: exporter
        image: iotistic/billing-exporter:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: billing-exporter-config
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: billing-exporter
  namespace: customer-abc
  labels:
    app: billing-exporter
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: billing-exporter
